-- Users tablosuna örnek veriler ekleme
insert into users (username, password, role) values ('user1', 'password1', 'ROLE_USER');
insert into users (username, password, role) values ('user2', 'password2', 'ROLE_USER');
insert into users (username, password, role) values ('user3', 'password3', 'ROLE_ADMIN');

-- Todos tablosuna örnek veriler ekleme
insert into todos (name, completed, end_date, user_id) values ('Strezhevoy', false, '2024-12-12', 1);
insert into todos (name, completed, end_date, user_id) values ('Ấp Tân Ngãi', false, '2024-11-15', 2);
insert into todos (name, completed, end_date, user_id) values ('Sundbyberg', false, '2024-10-22', 3);
insert into todos (name, completed, end_date, user_id) values ('Farinheiras', false, '2024-09-18', 1);
insert into todos (name, completed, end_date, user_id) values ('Niedźwiedź', false, '2024-08-30', 2);
insert into todos (name, completed, end_date, user_id) values ('Palhais', false, '2024-07-14', 3);
insert into todos (name, completed, end_date, user_id) values ('La Seyne-sur-Mer', true, '2024-06-28', 1);
insert into todos (name, completed, end_date, user_id) values ('Ravne', false, '2024-05-05', 2);
insert into todos (name, completed, end_date, user_id) values ('Cruz de los Milagros', true, '2024-04-10', 3);
insert into todos (name, completed, end_date, user_id) values ('Wakimachi', false, '2024-03-23', 1);
insert into todos (name, completed, end_date, user_id) values ('Joal-Fadiout', false, '2024-02-13', 2);
insert into todos (name, completed, end_date, user_id) values ('Magalalag', false, '2024-01-19', 3);
insert into todos (name, completed, end_date, user_id) values ('El Pino', false, '2023-12-08', 1);
insert into todos (name, completed, end_date, user_id) values ('Bailieborough', false, '2023-11-27', 2);
insert into todos (name, completed, end_date, user_id) values ('Tumaco', true, '2023-10-14', 3);
insert into todos (name, completed, end_date, user_id) values ('Xinchang', false, '2023-09-02', 1);
insert into todos (name, completed, end_date, user_id) values ('Bistrinci', false, '2023-08-15', 2);
insert into todos (name, completed, end_date, user_id) values ('‘Ūrīf', false, '2023-07-11', 3);
insert into todos (name, completed, end_date, user_id) values ('Anserma', false, '2023-06-23', 1);
insert into todos (name, completed, end_date, user_id) values ('Nagiba', false, '2023-05-06', 2);
insert into todos (name, completed, end_date, user_id) values ('Puerto La Cruz', true, '2023-04-21', 3);
insert into todos (name, completed, end_date, user_id) values ('Alebtong', false, '2023-03-13', 1);
insert into todos (name, completed, end_date, user_id) values ('Polepy', false, '2023-02-18', 2);
insert into todos (name, completed, end_date, user_id) values ('Zhuli', true, '2023-01-04', 3);
insert into todos (name, completed, end_date, user_id) values ('Burgos', false, '2022-12-20', 1);
insert into todos (name, completed, end_date, user_id) values ('Jugantang', false, '2022-11-17', 2);
insert into todos (name, completed, end_date, user_id) values ('Tongyuanpu', false, '2022-10-09', 3);
insert into todos (name, completed, end_date, user_id) values ('Bęczarka', false, '2022-09-25', 1);
insert into todos (name, completed, end_date, user_id) values ('Frisange', false, '2022-08-14', 2);
insert into todos (name, completed, end_date, user_id) values ('Avlónas', false, '2022-07-06', 3);
insert into todos (name, completed, end_date, user_id) values ('Same', true, '2022-06-28', 1);
insert into todos (name, completed, end_date, user_id) values ('Langob', false, '2022-05-12', 2);
insert into todos (name, completed, end_date, user_id) values ('Halong', false, '2022-04-27', 3);
insert into todos (name, completed, end_date, user_id) values ('Xiachu', false, '2022-03-10', 1);
insert into todos (name, completed, end_date, user_id) values ('Guanzhuang', false, '2022-02-25', 2);
insert into todos (name, completed, end_date, user_id) values ('Nanyang', true, '2022-01-08', 3);
insert into todos (name, completed, end_date, user_id) values ('Savannah', false, '2021-12-20', 1);
insert into todos (name, completed, end_date, user_id) values ('Charleston', false, '2021-11-30', 2);
insert into todos (name, completed, end_date, user_id) values ('Lillehammer', true, '2021-10-15', 3);
insert into todos (name, completed, end_date, user_id) values ('Liusi', false, '2021-09-07', 1);
insert into todos (name, completed, end_date, user_id) values ('Sedayulawas', false, '2021-08-24', 2);
insert into todos (name, completed, end_date, user_id) values ('Āgaro', false, '2021-07-01', 3);
insert into todos (name, completed, end_date, user_id) values ('Tumaco', false, '2021-06-19', 1);
insert into todos (name, completed, end_date, user_id) values ('Yigo Village', true, '2021-05-08', 2);
insert into todos (name, completed, end_date, user_id) values ('Sabugo', false, '2021-04-13', 3);
insert into todos (name, completed, end_date, user_id) values ('Nackawic', false, '2021-03-24', 1);
insert into todos (name, completed, end_date, user_id) values ('Lingdong', false, '2021-02-05', 2);
insert into todos (name, completed, end_date, user_id) values ('Jiangkou', true, '2021-01-14', 3);
insert into todos (name, completed, end_date, user_id) values ('Chvalšiny', false, '2020-12-30', 1);
insert into todos (name, completed, end_date, user_id) values ('Angra do Heroísmo', true, '2020-11-18', 2);
