insert into todos (name, completed) values ('Strezhevoy', false);
insert into todos (name, completed) values ('Ấp Tân Ngãi', false);
insert into todos (name, completed) values ('Sundbyberg', false);
insert into todos (name, completed) values ('Farinheiras', false);
insert into todos (name, completed) values ('Niedźwiedź', false);
insert into todos (name, completed) values ('Palhais', false);
insert into todos (name, completed) values ('La Seyne-sur-Mer', true);
insert into todos (name, completed) values ('Ravne', false);
insert into todos (name, completed) values ('Cruz de los Milagros', true);
insert into todos (name, completed) values ('Wakimachi', false);
insert into todos (name, completed) values ('Joal-Fadiout', false);
insert into todos (name, completed) values ('Magalalag', false);
insert into todos (name, completed) values ('El Pino', false);
insert into todos (name, completed) values ('Bailieborough', false);
insert into todos (name, completed) values ('Tumaco', true);
insert into todos (name, completed) values ('Xinchang', false);
insert into todos (name, completed) values ('Bistrinci', false);
insert into todos (name, completed) values ('‘Ūrīf', false);
insert into todos (name, completed) values ('Anserma', false);
insert into todos (name, completed) values ('Nagiba', false);
insert into todos (name, completed) values ('Puerto La Cruz', true);
insert into todos (name, completed) values ('Alebtong', false);
insert into todos (name, completed) values ('Polepy', false);
insert into todos (name, completed) values ('Zhuli', true);
insert into todos (name, completed) values ('Burgos', false);
insert into todos (name, completed) values ('Jugantang', false);
insert into todos (name, completed) values ('Tongyuanpu', false);
insert into todos (name, completed) values ('Bęczarka', false);
insert into todos (name, completed) values ('Frisange', false);
insert into todos (name, completed) values ('Avlónas', false);
insert into todos (name, completed) values ('Same', true);
insert into todos (name, completed) values ('Langob', false);
insert into todos (name, completed) values ('Halong', false);
insert into todos (name, completed) values ('Xiachu', false);
insert into todos (name, completed) values ('Guanzhuang', false);
insert into todos (name, completed) values ('Nanyang', true);
insert into todos (name, completed) values ('Savannah', false);
insert into todos (name, completed) values ('Charleston', false);
insert into todos (name, completed) values ('Lillehammer', true);
insert into todos (name, completed) values ('Liusi', false);
insert into todos (name, completed) values ('Sedayulawas', false);
insert into todos (name, completed) values ('Āgaro', false);
insert into todos (name, completed) values ('Tumaco', false);
insert into todos (name, completed) values ('Yigo Village', true);
insert into todos (name, completed) values ('Sabugo', false);
insert into todos (name, completed) values ('Nackawic', false);
insert into todos (name, completed) values ('Lingdong', false);
insert into todos (name, completed) values ('Jiangkou', true);
insert into todos (name, completed) values ('Chvalšiny', false);
insert into todos (name, completed) values ('Angra do Heroísmo', true);