insert into todos (name) values ('Strezhevoy');
insert into todos (name) values ('Ấp Tân Ngãi');
insert into todos (name) values ('Sundbyberg');
insert into todos (name) values ('Farinheiras');
insert into todos (name) values ('Niedźwiedź');
insert into todos (name) values ('Palhais');
insert into todos (name) values ('La Seyne-sur-Mer');
insert into todos (name) values ('Ravne');
insert into todos (name) values ('Cruz de los Milagros');
insert into todos (name) values ('Wakimachi');
insert into todos (name) values ('Joal-Fadiout');
insert into todos (name) values ('Magalalag');
insert into todos (name) values ('El Pino');
insert into todos (name) values ('Bailieborough');
insert into todos (name) values ('Tumaco');
insert into todos (name) values ('Xinchang');
insert into todos (name) values ('Bistrinci');
insert into todos (name) values ('‘Ūrīf');
insert into todos (name) values ('Anserma');
insert into todos (name) values ('Nagiba');
insert into todos (name) values ('Puerto La Cruz');
insert into todos (name) values ('Alebtong');
insert into todos (name) values ('Polepy');
insert into todos (name) values ('Zhuli');
insert into todos (name) values ('Burgos');
insert into todos (name) values ('Jugantang');
insert into todos (name) values ('Tongyuanpu');
insert into todos (name) values ('Bęczarka');
insert into todos (name) values ('Frisange');
insert into todos (name) values ('Avlónas');
insert into todos (name) values ('Same');
insert into todos (name) values ('Langob');
insert into todos (name) values ('Halong');
insert into todos (name) values ('Xiachu');
insert into todos (name) values ('Guanzhuang');
insert into todos (name) values ('Nanyang');
insert into todos (name) values ('Savannah');
insert into todos (name) values ('Charleston');
insert into todos (name) values ('Lillehammer');
insert into todos (name) values ('Liusi');
insert into todos (name) values ('Sedayulawas');
insert into todos (name) values ('Āgaro');
insert into todos (name) values ('Tumaco');
insert into todos (name) values ('Yigo Village');
insert into todos (name) values ('Sabugo');
insert into todos (name) values ('Nackawic');
insert into todos (name) values ('Lingdong');
insert into todos (name) values ('Jiangkou');
insert into todos (name) values ('Chvalšiny');
insert into todos (name) values ('Angra do Heroísmo');